package com.algorithms.leetcode.strings.easy;

/**
 * Given a string, we have to find out all subsequences of it. A String is a subsequence of a given
 * String, that is generated by deleting some character of a given string without changing its
 * order.
 *
 * @author yvenkatesh
 */
public class SubSequence {

  public static void main(String[] args) {
    String s = "abcd";

    for (int i = 0; i < s.length(); i++) {
      for (int j = 1; j < s.length() - i; j++) {
        System.out.println(s.substring(i, i + j));
      }
    }

  }

}
